apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dr-example
  namespace: argocd
spec:
  project: dr
  source:
    repoURL: https://github.com/ORG/gitops.git
    targetRevision: HEAD
    path: apps/example
  destination:
    name: dr-cluster
    namespace: example
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
