apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - name: example
                  path: apps/example
                  project: apps
          - list:
              elements:
                - cluster: prod
                  server: https://kubernetes.default.svc
                - cluster: dr
                  server: https://dr-cluster
  template:
    metadata:
      name: '{{ .name }}-{{ .cluster }}'
    spec:
      project: '{{ .project }}'
      source:
        repoURL: https://github.com/erickmaria/gitops.git
        targetRevision: HEAD
        path: '{{ .path }}'
      destination:
        server: '{{ .server }}'
        namespace: '{{ .name }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
