apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/erickmaria/gitops.git
        revision: HEAD
        directories:
          - path: clusters/*/infrastructure
            exclude: false
          - path: clusters/*/platform
            exclude: false
          - path: clusters/*/apps
            exclude: false
  template:
    metadata:
      name: '{{ .path.basename }}-{{ .path[1] }}'
    spec:
      project: '{{ .path[1] }}-config'
      source:
        repoURL: https://github.com/erickmaria/gitops.git
        targetRevision: HEAD
        path: '{{ .path.path }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
