apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - name: sealed-secrets
            path: apps/sealed-secrets
            namespace: sealed-secrets
            project: cluster-config
          - name: projects
            path: clusters/prod/infrastructure
            namespace: argocd
            project: cluster-config
            includeFile: projects.yaml
          - name: argocd-self
            path: clusters/prod/infrastructure/argocd
            namespace: argocd
            project: cluster-config
  template:
    metadata:
      name: '{{ .name }}'
    spec:
      project: '{{ .project }}'
      source:
        repoURL: https://github.com/erickmaria/gitops.git
        targetRevision: HEAD
        path: '{{ .path }}'
        directory:
          include: '{{ .includeFile }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
