apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-config
  namespace: argocd
spec:
  description: Configuração de cluster (infraestrutura e plataforma)
  sourceRepos:
    - https://github.com/erickmaria/gitops.git
  destinations:
    - server: https://kubernetes.default.svc
    - namespace: sealed-secrets
    - namespace: argocd
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd
spec:
  description: Aplicações de negócio
  sourceRepos:
    - https://github.com/erickmaria/gitops.git
  destinations:
    - namespace: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dr
  namespace: argocd
spec:
  description: Apps gerenciadas no cluster de DR (spoke)
  sourceRepos:
    - https://github.com/erickmaria/gitops.git
  destinations:
    - name: dr-cluster
      namespace: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
