redis-ha:
  enabled: false

controller:
  replicas: 1

server:
  replicas: 1

repoServer:
  replicas: 1

applicationSet:
  replicas: 1

configs:
  cm:
    kustomize.buildOptions: --enable-helm
    accounts.argo-preview: apiKey
  rbac:
    policy.csv: |
      g, baylin2, role:readonly
  # params:
  #   server.insecure: true 