redis-ha:
  enabled: false

controller:
  replicas: 1

server:
  replicas: 1
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      # Fixes the ERR_TOO_MANY_REDIRECTS loop
      # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      # Recommended NGINX settings for Argo CD
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "60"


repoServer:
  replicas: 1

applicationSet:
  replicas: 1

configs:
  cm:
    kustomize.buildOptions: --enable-helm
    accounts.argo-preview: apiKey
  rbac:
    policy.csv: |
      g, argo-preview, role:admin
  # params:
  #   server.insecure: true 