apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          # Adicione aqui novos componentes de plataforma:
          # - name: kube-prometheus-stack
          #   path: apps/kube-prometheus-stack
          #   namespace: monitoring
          - name: placeholder
            path: apps/example
            namespace: example
            project: cluster-config
  template:
    metadata:
      name: platform-{{ .name }}
    spec:
      project: '{{ .project }}'
      source:
        repoURL: https://github.com/erickmaria/gitops.git
        targetRevision: HEAD
        path: '{{ .path }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
