apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-self
  namespace: argocd
spec:
  project: cluster-config
  source:
    repoURL: https://github.com/erickmaria/gitops.git
    targetRevision: HEAD
    path: clusters/prod/infrastructure/argocd
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
